import type { CustomCellRendererProps } from "@ag-grid-community/react";
import { type FunctionComponent } from "react";

const countryFlagMap: Record<string, string> = {
    "Afghanistan": "https://flags.fmcdn.net/data/flags/mini/af.png",
    "Albania": "https://flags.fmcdn.net/data/flags/mini/al.png",
    "Algeria": "https://flags.fmcdn.net/data/flags/mini/dz.png",
    "Andorra": "https://flags.fmcdn.net/data/flags/mini/ad.png",
    "Angola": "https://flags.fmcdn.net/data/flags/mini/ao.png",
    "Antigua and Barbuda": "https://flags.fmcdn.net/data/flags/mini/ag.png",
    "Argentina": "https://flags.fmcdn.net/data/flags/mini/ar.png",
    "Armenia": "https://flags.fmcdn.net/data/flags/mini/am.png",
    "Australia": "https://flags.fmcdn.net/data/flags/mini/au.png",
    "Austria": "https://flags.fmcdn.net/data/flags/mini/at.png",
    "Azerbaijan": "https://flags.fmcdn.net/data/flags/mini/az.png",
    "Bahamas": "https://flags.fmcdn.net/data/flags/mini/bs.png",
    "Bahrain": "https://flags.fmcdn.net/data/flags/mini/bh.png",
    "Bangladesh": "https://flags.fmcdn.net/data/flags/mini/bd.png",
    "Barbados": "https://flags.fmcdn.net/data/flags/mini/bb.png",
    "Belarus": "https://flags.fmcdn.net/data/flags/mini/by.png",
    "Belgium": "https://flags.fmcdn.net/data/flags/mini/be.png",
    "Belize": "https://flags.fmcdn.net/data/flags/mini/bz.png",
    "Benin": "https://flags.fmcdn.net/data/flags/mini/bj.png",
    "Bhutan": "https://flags.fmcdn.net/data/flags/mini/bt.png",
    "Bolivia": "https://flags.fmcdn.net/data/flags/mini/bo.png",
    "Bosnia and Herzegovina": "https://flags.fmcdn.net/data/flags/mini/ba.png",
    "Botswana": "https://flags.fmcdn.net/data/flags/mini/bw.png",
    "Brazil": "https://flags.fmcdn.net/data/flags/mini/br.png",
    "Brunei": "https://flags.fmcdn.net/data/flags/mini/bn.png",
    "Bulgaria": "https://flags.fmcdn.net/data/flags/mini/bg.png",
    "Burkina Faso": "https://flags.fmcdn.net/data/flags/mini/bf.png",
    "Burundi": "https://flags.fmcdn.net/data/flags/mini/bi.png",
    "Cabo Verde": "https://flags.fmcdn.net/data/flags/mini/cv.png",
    "Cambodia": "https://flags.fmcdn.net/data/flags/mini/kh.png",
    "Cameroon": "https://flags.fmcdn.net/data/flags/mini/cm.png",
    "Canada": "https://flags.fmcdn.net/data/flags/mini/ca.png",
    "Central African Republic": "https://flags.fmcdn.net/data/flags/mini/cf.png",
    "Chad": "https://flags.fmcdn.net/data/flags/mini/td.png",
    "Chile": "https://flags.fmcdn.net/data/flags/mini/cl.png",
    "China": "https://flags.fmcdn.net/data/flags/mini/cn.png",
    "Colombia": "https://flags.fmcdn.net/data/flags/mini/co.png",
    "Comoros": "https://flags.fmcdn.net/data/flags/mini/km.png",
    "Costa Rica": "https://flags.fmcdn.net/data/flags/mini/cr.png",
    "Croatia": "https://flags.fmcdn.net/data/flags/mini/hr.png",
    "Cuba": "https://flags.fmcdn.net/data/flags/mini/cu.png",
    "Cyprus": "https://flags.fmcdn.net/data/flags/mini/cy.png",
    "Czechia (Czech Republic)": "https://flags.fmcdn.net/data/flags/mini/cz.png",
    "Denmark": "https://flags.fmcdn.net/data/flags/mini/dk.png",
    "Djibouti": "https://flags.fmcdn.net/data/flags/mini/dj.png",
    "Dominica": "https://flags.fmcdn.net/data/flags/mini/dm.png",
    "Dominican Republic": "https://flags.fmcdn.net/data/flags/mini/do.png",
    "Ecuador": "https://flags.fmcdn.net/data/flags/mini/ec.png",
    "Egypt": "https://flags.fmcdn.net/data/flags/mini/eg.png",
    "El Salvador": "https://flags.fmcdn.net/data/flags/mini/sv.png",
    "Equatorial Guinea": "https://flags.fmcdn.net/data/flags/mini/gq.png",
    "Eritrea": "https://flags.fmcdn.net/data/flags/mini/er.png",
    "Estonia": "https://flags.fmcdn.net/data/flags/mini/ee.png",
    "Eswatini (fmr. 'Swaziland')": "https://flags.fmcdn.net/data/flags/mini/sz.png",
    "Ethiopia": "https://flags.fmcdn.net/data/flags/mini/et.png",
    "Fiji": "https://flags.fmcdn.net/data/flags/mini/fj.png",
    "Finland": "https://flags.fmcdn.net/data/flags/mini/fi.png",
    "France": "https://flags.fmcdn.net/data/flags/mini/fr.png",
    "Gabon": "https://flags.fmcdn.net/data/flags/mini/ga.png",
    "Gambia": "https://flags.fmcdn.net/data/flags/mini/gm.png",
    "Georgia": "https://flags.fmcdn.net/data/flags/mini/ge.png",
    "Germany": "https://flags.fmcdn.net/data/flags/mini/de.png",
    "Ghana": "https://flags.fmcdn.net/data/flags/mini/gh.png",
    "Greece": "https://flags.fmcdn.net/data/flags/mini/gr.png",
    "Grenada": "https://flags.fmcdn.net/data/flags/mini/gd.png",
    "Guatemala": "https://flags.fmcdn.net/data/flags/mini/gt.png",
    "Guinea": "https://flags.fmcdn.net/data/flags/mini/gn.png",
    "Guinea-Bissau": "https://flags.fmcdn.net/data/flags/mini/gw.png",
    "Guyana": "https://flags.fmcdn.net/data/flags/mini/gy.png",
    "Haiti": "https://flags.fmcdn.net/data/flags/mini/ht.png",
    "Honduras": "https://flags.fmcdn.net/data/flags/mini/hn.png",
    "Hungary": "https://flags.fmcdn.net/data/flags/mini/hu.png",
    "Iceland": "https://flags.fmcdn.net/data/flags/mini/is.png",
    "India": "https://flags.fmcdn.net/data/flags/mini/in.png",
    "Indonesia": "https://flags.fmcdn.net/data/flags/mini/id.png",
    "Iran": "https://flags.fmcdn.net/data/flags/mini/ir.png",
    "Iraq": "https://flags.fmcdn.net/data/flags/mini/iq.png",
    "Ireland": "https://flags.fmcdn.net/data/flags/mini/ie.png",
    "Israel": "https://flags.fmcdn.net/data/flags/mini/il.png",
    "United States of America": "https://flagcdn.com/w320/us.png",
    "United States Minor Outlying Islands": "https://flagcdn.com/w320/um.png",
    "Christmas Island": "https://flagcdn.com/w320/cx.png",
    "Pitcairn Islands": "https://flagcdn.com/w320/pn.png",
    "Anguilla": "https://flagcdn.com/w320/ai.png",
    "Antarctica": "https://flagcdn.com/w320/aq.png",
    "Italy": "https://flags.fmcdn.net/data/flags/mini/it.png",
    "Jamaica": "https://flags.fmcdn.net/data/flags/mini/jm.png",
    "Japan": "https://flags.fmcdn.net/data/flags/mini/jp.png",
    "Jordan": "https://flags.fmcdn.net/data/flags/mini/jo.png",
    "Kazakhstan": "https://flags.fmcdn.net/data/flags/mini/kz.png",
    "Kenya": "https://flags.fmcdn.net/data/flags/mini/ke.png",
    "Kiribati": "https://flags.fmcdn.net/data/flags/mini/ki.png",
    "Korea, North": "https://flags.fmcdn.net/data/flags/mini/kp.png",
    "Korea, South": "https://flags.fmcdn.net/data/flags/mini/kr.png",
    "Kosovo": "https://flags.fmcdn.net/data/flags/mini/xk.png",
    "Kuwait": "https://flags.fmcdn.net/data/flags/mini/kw.png",
    "Kyrgyzstan": "https://flags.fmcdn.net/data/flags/mini/kg.png",
    "Latvia": "https://flags.fmcdn.net/data/flags/mini/lv.png",
    "Lebanon": "https://flags.fmcdn.net/data/flags/mini/lb.png",
    "Lesotho": "https://flags.fmcdn.net/data/flags/mini/ls.png",
    "Liberia": "https://flags.fmcdn.net/data/flags/mini/lr.png",
    "Libya": "https://flags.fmcdn.net/data/flags/mini/ly.png",
    "Liechtenstein": "https://flags.fmcdn.net/data/flags/mini/li.png",
    "Lithuania": "https://flags.fmcdn.net/data/flags/mini/lt.png",
    "Luxembourg": "https://flags.fmcdn.net/data/flags/mini/lu.png",
    "Madagascar": "https://flags.fmcdn.net/data/flags/mini/mg.png",
    "Malawi": "https://flags.fmcdn.net/data/flags/mini/mw.png",
    "Malaysia": "https://flags.fmcdn.net/data/flags/mini/my.png",
    "Maldives": "https://flags.fmcdn.net/data/flags/mini/mv.png",
    "Mali": "https://flags.fmcdn.net/data/flags/mini/ml.png",
    "Malta": "https://flags.fmcdn.net/data/flags/mini/mt.png",
    "Marshall Islands": "https://flags.fmcdn.net/data/flags/mini/mh.png",
    "Mauritania": "https://flags.fmcdn.net/data/flags/mini/mr.png",
    "Mauritius": "https://flags.fmcdn.net/data/flags/mini/mu.png",
    "Mexico": "https://flags.fmcdn.net/data/flags/mini/mx.png",
    "Micronesia": "https://flags.fmcdn.net/data/flags/mini/fm.png",
    "Moldova": "https://flags.fmcdn.net/data/flags/mini/md.png",
    "Monaco": "https://flags.fmcdn.net/data/flags/mini/mc.png",
    "Mongolia": "https://flags.fmcdn.net/data/flags/mini/mn.png",
    "Montenegro": "https://flags.fmcdn.net/data/flags/mini/me.png",
    "Morocco": "https://flags.fmcdn.net/data/flags/mini/ma.png",
    "Mozambique": "https://flags.fmcdn.net/data/flags/mini/mz.png",
    "Myanmar (formerly Burma)": "https://flags.fmcdn.net/data/flags/mini/mm.png",
    "Namibia": "https://flags.fmcdn.net/data/flags/mini/na.png",
    "Nauru": "https://flags.fmcdn.net/data/flags/mini/nr.png",
    "Nepal": "https://flags.fmcdn.net/data/flags/mini/np.png",
    "Netherlands": "https://flags.fmcdn.net/data/flags/mini/nl.png",
    "New Zealand": "https://flags.fmcdn.net/data/flags/mini/nz.png",
    "Nicaragua": "https://flags.fmcdn.net/data/flags/mini/ni.png",
    "Niger": "https://flags.fmcdn.net/data/flags/mini/ne.png",
    "Nigeria": "https://flags.fmcdn.net/data/flags/mini/ng.png",
    "North Macedonia": "https://flags.fmcdn.net/data/flags/mini/mk.png",
    "Norway": "https://flags.fmcdn.net/data/flags/mini/no.png",
    "Oman": "https://flags.fmcdn.net/data/flags/mini/om.png",
    "Pakistan": "https://flags.fmcdn.net/data/flags/mini/pk.png",
    "Palau": "https://flags.fmcdn.net/data/flags/mini/pw.png",
    "Panama": "https://flags.fmcdn.net/data/flags/mini/pa.png",
    "Papua New Guinea": "https://flags.fmcdn.net/data/flags/mini/pg.png",
    "Paraguay": "https://flags.fmcdn.net/data/flags/mini/py.png",
    "Peru": "https://flags.fmcdn.net/data/flags/mini/pe.png",
    "Philippines": "https://flags.fmcdn.net/data/flags/mini/ph.png",
    "Poland": "https://flags.fmcdn.net/data/flags/mini/pl.png",
    "Portugal": "https://flags.fmcdn.net/data/flags/mini/pt.png",
    "Qatar": "https://flags.fmcdn.net/data/flags/mini/qa.png",
    "Romania": "https://flags.fmcdn.net/data/flags/mini/ro.png",
    "Russia": "https://flags.fmcdn.net/data/flags/mini/ru.png",
    "Rwanda": "https://flags.fmcdn.net/data/flags/mini/rw.png",
    "Saint Kitts and Nevis": "https://flags.fmcdn.net/data/flags/mini/kn.png",
    "Saint Lucia": "https://flags.fmcdn.net/data/flags/mini/lc.png",
    "Saint Vincent and the Grenadines": "https://flags.fmcdn.net/data/flags/mini/vc.png",
    "Samoa": "https://flags.fmcdn.net/data/flags/mini/ws.png",
    "San Marino": "https://flags.fmcdn.net/data/flags/mini/sm.png",
    "Sao Tome and Principe": "https://flags.fmcdn.net/data/flags/mini/st.png",
    "Saudi Arabia": "https://flags.fmcdn.net/data/flags/mini/sa.png",
    "Senegal": "https://flags.fmcdn.net/data/flags/mini/sn.png",
    "Serbia": "https://flags.fmcdn.net/data/flags/mini/rs.png",
    "Seychelles": "https://flags.fmcdn.net/data/flags/mini/sc.png",
    "Sierra Leone": "https://flags.fmcdn.net/data/flags/mini/sl.png",
    "Singapore": "https://flags.fmcdn.net/data/flags/mini/sg.png",
    "Slovakia": "https://flags.fmcdn.net/data/flags/mini/sk.png",
    "Slovenia": "https://flags.fmcdn.net/data/flags/mini/si.png",
    "Solomon Islands": "https://flags.fmcdn.net/data/flags/mini/sb.png",
    "Somalia": "https://flags.fmcdn.net/data/flags/mini/so.png",
    "South Africa": "https://flags.fmcdn.net/data/flags/mini/za.png",
    "South Sudan": "https://flags.fmcdn.net/data/flags/mini/ss.png",
    "Spain": "https://flags.fmcdn.net/data/flags/mini/es.png",
    "Sri Lanka": "https://flags.fmcdn.net/data/flags/mini/lk.png",
    "Sudan": "https://flags.fmcdn.net/data/flags/mini/sd.png",
    "Suriname": "https://flags.fmcdn.net/data/flags/mini/sr.png",
    "Sweden": "https://flags.fmcdn.net/data/flags/mini/se.png",
    "Switzerland": "https://flags.fmcdn.net/data/flags/mini/ch.png",
    "Syria": "https://flags.fmcdn.net/data/flags/mini/sy.png",
    "Tajikistan": "https://flags.fmcdn.net/data/flags/mini/tj.png",
    "Tanzania": "https://flags.fmcdn.net/data/flags/mini/tz.png",
    "Thailand": "https://flags.fmcdn.net/data/flags/mini/th.png",
    "Timor-Leste": "https://flags.fmcdn.net/data/flags/mini/tl.png",
    "Togo": "https://flags.fmcdn.net/data/flags/mini/tg.png",
    "Tonga": "https://flags.fmcdn.net/data/flags/mini/to.png",
    "Trinidad and Tobago": "https://flags.fmcdn.net/data/flags/mini/tt.png",
    "Tunisia": "https://flags.fmcdn.net/data/flags/mini/tn.png",
    "Turkey": "https://flags.fmcdn.net/data/flags/mini/tr.png",
    "Turkmenistan": "https://flags.fmcdn.net/data/flags/mini/tm.png",
    "Tuvalu": "https://flags.fmcdn.net/data/flags/mini/tv.png",
    "Uganda": "https://flags.fmcdn.net/data/flags/mini/ug.png",
    "Ukraine": "https://flags.fmcdn.net/data/flags/mini/ua.png",
    "United Arab Emirates": "https://flags.fmcdn.net/data/flags/mini/ae.png",
    "United Kingdom": "https://flags.fmcdn.net/data/flags/mini/gb.png",
    "United States": "https://flags.fmcdn.net/data/flags/mini/us.png",
    "Uruguay": "https://flags.fmcdn.net/data/flags/mini/uy.png",
    "Uzbekistan": "https://flags.fmcdn.net/data/flags/mini/uz.png",
    "Vanuatu": "https://flags.fmcdn.net/data/flags/mini/vu.png",
    "Vatican City": "https://flags.fmcdn.net/data/flags/mini/va.png",
    "Venezuela": "https://flags.fmcdn.net/data/flags/mini/ve.png",
    "Vietnam": "https://flags.fmcdn.net/data/flags/mini/vn.png",
    "Zimbabwe": "https://flags.fmcdn.net/data/flags/mini/zw.png",
    "Zambia": "https://flags.fmcdn.net/data/flags/mini/zm.png",
    "American Samoa": "https://flags.fmcdn.net/data/flags/mini/as.png",
    "Hong Kong": "https://flags.fmcdn.net/data/flags/mini/hk.png",
    "Mayotte": "https://flagcdn.com/w320/mu.png",
    "Republic of Korea": "https://flagcdn.com/w320/kr.png",
    "Laos": "https://flags.fmcdn.net/data/flags/mini/la.png",
    "Aruba": "https://flags.fmcdn.net/data/flags/mini/aw.png",
    "Congo": "https://flags.fmcdn.net/data/flags/mini/cg.png",
    "Myanmar": "https://flags.fmcdn.net/data/flags/mini/mm.png",
    "Jersey": "https://flags.fmcdn.net/data/flags/mini/je.png",
    "Taiwan": "https://flags.fmcdn.net/data/flags/mini/tw.png"




    // Add other countries as needed...
};

export const CountryCellRenderer: FunctionComponent<CustomCellRendererProps> = ({
    value,
  }) => (
    <div style={{ display: "flex", alignItems: "center" }}>
        {value && countryFlagMap[value] && (
            <img
                src={countryFlagMap[value]}
                alt={value}
                style={{ width: "20px", height: "15px", marginRight: "10px" }}
            />
        )}
        <span>{value}</span>
    </div>
);
